import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
const root = process.cwd();
const page=fs.readFileSync(path.join(root,"app/page.tsx"),"utf8");
const profile=fs.readFileSync(path.join(root,"app/api/profile/route.ts"),"utf8");
const gemini=fs.readFileSync(path.join(root,"lib/server/gemini.ts"),"utf8");
const chat=fs.readFileSync(path.join(root,"app/api/chat/route.ts"),"utf8");
const loader=fs.readFileSync(path.join(root,"lib/server/character-loader.ts"),"utf8");
const checks=[]; const check=(n,p)=>checks.push([n,Boolean(p)]);
check("character suggestions show only names", page.includes("homeSearchSuggestions.map(c=><button") && !page.includes('<Avatar character={c} size={32}/><span><strong>{c.name}</strong><small>{c.creator}'));
check("character creation has server-side quota", profile.includes('SELECT COUNT(*) AS count FROM user_bots WHERE owner_id=?') && profile.includes("maxBots = 30"));
check("character creation validates bounded fields", profile.includes("name.length > 80") && profile.includes("personality.length > 6000") && profile.includes("exampleMessages.length > 8"));
check("character update is owner-only", profile.includes('action === "update-bot"') && profile.includes("existing.owner_id") && profile.includes("UPDATE user_bots"));
check("character deletion is owner-only", profile.includes('action === "delete-bot"') && profile.includes("DELETE FROM user_bots") && profile.includes("existing.owner_id"));
check("character edit UI exists", page.includes("startEditBot") && page.includes("Save changes"));
check("character delete UI exists", page.includes("deleteBot") && page.includes("Delete"));
check("create/edit modal resets correctly", page.includes("setEditingBotId(null)") && page.includes("emptyBotForm"));
check("Gemini retries transient 429/503", gemini.includes("retryDelaysMs = [1000, 2000]") && gemini.includes("[429, 503]"));
check("provider transient errors get friendly chat messages", chat.includes("temporarily unavailable or overloaded") && chat.includes("[429, 500, 502, 503, 504]"));
check("chat loads canonical character server-side", chat.includes("loadCanonicalCharacterForUser") && loader.includes("getCharacter(id)") && loader.includes("row.visibility") && loader.includes("row.owner_id"));
check("phase 43 checker parses", (()=>{try{execFileSync(process.execPath,["--check",path.join(root,"scripts/check-phase43.mjs")],{stdio:"ignore"});return true}catch{return false}})());
let ok=0; for(const [n,p] of checks){console.log(`${p?"OK":"FAIL"} — ${n}`);if(p)ok++;} console.log(`Phase 43 stability/characters checks: ${ok}/${checks.length} OK`); if(ok!==checks.length)process.exit(1);
