import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
const root = process.cwd();
const page = fs.readFileSync(path.join(root,"app/page.tsx"),"utf8");
const community = fs.readFileSync(path.join(root,"app/api/community/route.ts"),"utf8");
const css = fs.readFileSync(path.join(root,"app/globals.css"),"utf8");
const checks=[]; const check=(n,p)=>checks.push([n,Boolean(p)]);
check("home search does not replace home while typing", page.includes("homeSearchSubmitted") && page.includes("setHomeSearchSubmitted(false)"));
check("home search has character/creator modes", page.includes('searchMode==="characters"') && page.includes("Creators") && page.includes("Characters"));
check("character search opens chat", page.includes("onClick={()=>openCharacter(c)}"));
check("creator search uses public bots", community.includes("b.visibility='public'") && community.includes('mode === "creators"'));
check("creator results aggregate public bot names", page.includes("Character(s):") && community.includes("botsByOwner"));
check("creator interactions are aggregated without conversation text", community.includes("interactionByBot") && community.includes("JOIN messages m") && !community.includes("SELECT conversations_json"));
check("public profile can be opened from search", page.includes("openProfile(c.id)") && page.includes("async function openProfile(id?: string)"));
check("bot results show interactions and creator", page.includes("search-result-meta") && page.includes("MessageCircle") && page.includes("c.creator"));
check("explore groups public bots by server-provided categories", page.includes("exploreCategories") && page.includes("categories.action") && page.includes("categories.anime"));
check("premium comparison text is enlarged", css.includes(".premium-comparison-row>span strong{font-size:13px") && css.includes(".premium-comparison-row>span small{font-size:11px"));
check("phase 42 checker parses", (()=>{try{execFileSync(process.execPath,["--check",path.join(root,"scripts/check-phase42.mjs")],{stdio:"ignore"});return true}catch{return false}})());
let ok=0; for(const [n,p] of checks){console.log(`${p?"OK":"FAIL"} — ${n}`);if(p)ok++;} console.log(`Phase 42 search/community/premium checks: ${ok}/${checks.length} OK`); if(ok!==checks.length)process.exit(1);
